logging:
  level:
    org.jooq.tools: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cringe
    username: postgres
    password: root